package main

import (
	"bytes"
	"github.com/stretchr/testify/assert"
	"strings"
	"testing"
)

func TestMagicNumberMapping(t *testing.T) {
	script := `id magicnumber field mn magic 0x0110ff end`
	mapping, err := parseMapping(strings.NewReader(script))
	assert.NoError(t, err)
	assert.Len(t, mapping.Fields, 1)
	assert.Equal(t, []byte{0x01, 0x10, 0xff}, mapping.Fields[0].MagicNumber)
	assert.Equal(t, "0x1, 0x10, 0xff", mapping.Fields[0].MagicNumberValues())
}

func TestMagicNumberOutput(t *testing.T) {
	script := `id magicNumber field mn magic 0x0110ff field anInt u16 end`
	mapping, err := parseMapping(strings.NewReader(script))
	assert.NoError(t, err)
	mapping.Package = "mapping"

	const expected = `// Code generated by bingen. DO NOT EDIT.
package mapping

import (
	"encoding/binary"
	"github.com/saylorsolutions/binmap"
	"io"
)

type MagicNumber struct {
	AnInt uint16
}

func (t *MagicNumber) mapper() bin.Mapper {
	return bin.MapSequence(
		bin.MagicNumber([]byte(0x1, 0x10, 0xff)),
		bin.Int[uint16](&t.AnInt),
	)
}

func MagicNumberMapper(t *MagicNumber) bin.Mapper {
	return t.mapper()
}

func (t *MagicNumber) Read(r io.Reader, endian binary.ByteOrder) error {
	return t.mapper().Read(r, endian)
}

func (t *MagicNumber) Write(w io.Writer, endian binary.ByteOrder) error {
	return t.mapper().Write(w, endian)
}
`
	var buf bytes.Buffer
	assert.NoError(t, genTempl.Execute(&buf, mapping))
	assert.Equal(t, expected, buf.String())
}
